name: The Caterpillar Project
description: A large suite of dark matter simulations of Milky Way-sized galaxies.
url: http://caterpillarproject.org
markdown: redcarpet
highlighter: pygments
permalink: /about/:title